### PR TITLE
Update the "Forbidden usernames" UI

### PR DESCRIPTION
**Pull request by gabek**
Give it a real add/remove UI.  This uses a new generic add/remove from array control so future array management can be done by throwing this in.

image

Closes https://github.com/owncast/owncast/issues/1230

/cc @MFTabriz

### CODE REVIEW

**Comment by MFTabriz** [comment]
After removing all the forbidden usernames, it reverts back to the default list: "owncast, operator, admin, system". Is this the intended behavior?

**Comment by gabek** [comment]
Yes, there's a list of defaults that are used if the setting is empty.

**Comment by gingervitis** [comment]
I made some css-ish updates to the branch

**Review by gingervitis — APPROVED** [review]
lgtm

**Pull request merged**
