### PR TITLE
Increase Welcome Message maxLength

### PR DESCRIPTION
**Pull request by f35f0ef9d0e827dae86552d3899f78fc**
TEXTFIELD_PROPS_SERVER_WELCOME_MESSAGE.maxLength = 2500
Fixes #1595

I didn't find anywhere to add an entry to a changelog. Contributing looks pretty laid-back. Let me know if there is anything else you'd like me to add for this.

I'm not a UI guy, but maybe an expandable text field should go along with this change.

### CODE REVIEW

**Comment by gabek** [comment]
Ignore the linter failure. I'm not sure why it fails when it doesn't have write permissions to the repo. I filed https://github.com/owncast/owncast/issues/1607 to look into it.

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
Sure, but I have nothing to do at this point. The next step is for you to ignore the linter and then merge the PR if I'm not mistaken. I don't have Write access and so cannot merge myself.

**Comment by gabek** [comment]
Oh yeah, I just didn't want you to think you did anything wrong because it failed, that's all.

**Comment by gabek** [comment]
Are you interested in expanding our text field control to allow for expanding?  We use the Ant Design controls, and it seems straightforward here: https://ant.design/components/input/#components-input-demo-autosize-textarea

Maybe we'd need a new `autosize` bool on our `FormTextField` that wraps the Ant Design `Field`.

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
Yeah, I'm interested. I will look into it within a few days.

**Comment by gabek** [comment]
Awesome!  I went ahead and filed https://github.com/owncast/owncast/issues/1611 for that.

Thanks for this tweak!

**Pull request merged**
